### PR TITLE
Fix mbedTLS AES-CBC backend: avoid BAD_INPUT_DATA during cipher_finish() in SSH handshake

### LINKED ISSUE #793: Hitting error -44 "Unable to ask for ssh-userauth service" with mbedtls
**Describe the bug**

When downloading from SFTP via libcurl, I am hitting error code -44 with description "Unable to ask for ssh-userauth service". This happens for one particular SFTP server, and others work fine.

**To Reproduce**

I _think_ it has to do with server using aes256-cbc algorithm. As I have no control over the server, I'm trying to verify that assumption by changing advertised set of Ciphers on my side.

**Expected behavior**

I would like it to work :-D

**Version (please complete the following information):**
 - OS and version: Julia 1.8.5 running on Ubuntu Linux 22.04
 - libssh2 version: 1.10.0
 - crypto backend: MbedTLS

**Additional context**

It seems to fail to send encrypt the message before sending it. Relevant code [here](https://github.com/libssh2/libssh2/blob/821d50dad313b53fb2782f26aec1f52f1be34fc0/src/session.c#L775) and [here](https://github.com/libssh2/libssh2/blob/1e1a74eb7e97b004ccad86a32c1874eb0d986d6f/src/transport.c#L896).

I have found a similar issue [here](https://github.com/libssh2/libssh2/issues/463) which was resolved by fixing how openssl functions called [here](https://github.com/libssh2/libssh2/pull/556). I assume this might be a similar issue with mbedtls, but I'd be hard pressed to find out exactly what's wrong.

### PR DESCRIPTION
**Pull request by AdrianMoranMontes**
# Description

This PR fixes a reproducible failure in the mbedTLS backend of libssh2 when negotiating AES-CBC ciphers with certain SSH servers.

When libssh2 is built with mbedTLS (tested with mbedTLS 3.6.2), the library fails to encrypt the very first SSH packet after NEWKEYS when the chosen cipher is AES-XXX-CBC. The failure manifests as:

```shell
Failure establishing SSH session: -44
libssh2 last error: Unable to ask for ssh-userauth service
```

Tracing the mbedTLS backend reveals the root cause:

```shell
mbedTLS cipher_finish failed: ret = -24832 (MBEDTLS_ERR_CIPHER_BAD_INPUT_DATA)
mbedTLS cipher_crypt failed
crypt name = aes256-cbc
```

This happens during the encryption of SSH_MSG_SERVICE_REQUEST (seqno=0), right after the KEX exchange succeeds.
The server → client traffic is irrelevant at that point; this is a pure client-side mbedTLS cipher failure.

# Reproduction steps

The issue can be reproduced with:

   - libssh2 master
   - mbedTLS 3.6.2
   - any SSH server that negotiates AES-128-CBC or AES-256-CBC
(confirmed with OpenSSH and a proprietary embedded SSH server)

Steps:

   1. Build libssh2 with mbedTLS backend.
   2. Connect to a server offering CBC ciphers.
   3. Let the negotiation select AES-CBC.
   4. Observe handshake failure right after NEWKEYS.

# Root cause analysis

1. Wrong interpretation of the `encrypt` flag

The code used:

```c
op = encrypt == 0 ? MBEDTLS_ENCRYPT : MBEDTLS_DECRYPT;
```

which inverted the intended direction.
The fix correctly maps the flag:

```c
op = encrypt ? MBEDTLS_ENCRYPT : MBEDTLS_DECRYPT;
```

2. Missing explicit padding configuration for mbedTLS

libssh2 handles SSH packet padding internally, so the cipher must operate with no padding.
Without explicitly setting this, mbedTLS rejects CBC operations during `cipher_finish()`.

The fix adds:

```c
mbedtls_cipher_set_padding_mode(ctx, MBEDTLS_PADDING_NONE);
```

This ensures that mbedTLS does not attempt to validate or add padding at the cipher layer.

# Related issues

Probably, this PR fixes #793

### CODE REVIEW

**Review by vszakats — DISMISSED** [review]

File: src/mbedtls.c [hunk 1]
```diff
@@ -119,14 +119,28 @@ _libssh2_mbedtls_cipher_init(_libssh2_cipher_ctx *ctx,
     if(!ctx)
         return -1;
 
-    op = encrypt == 0 ? MBEDTLS_ENCRYPT : MBEDTLS_DECRYPT;
+    op = encrypt ? MBEDTLS_ENCRYPT : MBEDTLS_DECRYPT;
```
Comment (vszakats) [inline src/mbedtls.c]: Makes me wonder how could libssh2 + mbedTLS work correctly before if this condition
was reversed all along?
